apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "eks-apr-base"
  annotations:
    github.com/project-slug: veecode-platform/eks-apr-base
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/admin"
