apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "eks-apr-base"
  annotations:
    github.com/project-slug: veecode-platform/eks-apr-base
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
